FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . /app/
RUN mkdir -p /vol/web/media
EXPOSE 8000
CMD ["/bin/sh", "/app/entrypoint.sh"]
